import { useState, useRef } from "react";
import { invokeLLM } from "@/lib/api";
import { uploadFile } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScanSearch, ImageIcon, FileText, X, AlertCircle } from "lucide-react";

export default function AIDetector() {
  const [mode, setMode] = useState("text"); // "text" | "image"
  const [input, setInput] = useState("");
  const [imageFile, setImageFile] = useState(null); // { name, url, preview }
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");
  const fileInputRef = useRef(null);

  const handleImageChange = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    // Validate file size (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      setError("Image size must be less than 10MB");
      return;
    }
    
    // Validate file type
    if (!file.type.startsWith("image/")) {
      setError("Please upload a valid image file");
      return;
    }
    
    setError("");
    setUploading(true);
    setResult(null);
    
    try {
      const preview = URL.createObjectURL(file);
      const { file_url } = await uploadFile(file);
      setImageFile({ name: file.name, url: file_url, preview });
    } catch (err) {
      console.error("Upload error:", err);
      setError("Failed to upload image. Please try again.");
    } finally {
      setUploading(false);
      e.target.value = "";
    }
  };

  const detect = async () => {
    if (mode === "text" && !input.trim()) {
      setError("Please enter some text to analyze");
      return;
    }
    if (mode === "image" && !imageFile) {
      setError("Please upload an image to analyze");
      return;
    }
    
    setError("");
    setLoading(true);
    setResult(null);

    try {
      const prompt = mode === "text"
        ? `Analyze the following text and determine whether it was written by a human or generated by an AI.

Return a JSON object with:
- "verdict": either "AI-Generated" or "Human-Written"
- "confidence": a percentage number (0-100) of how confident you are
- "reasoning": a 2-3 sentence explanation of key signals that led to this conclusion

Text to analyze:
"""
${input}
"""`
        : `Analyze the attached image and determine whether it was generated by an AI (e.g. Midjourney, DALL-E, Stable Diffusion) or is a real photograph taken by a human.

Return a JSON object with:
- "verdict": either "AI-Generated" or "Real Photo"
- "confidence": a percentage number (0-100) of how confident you are
- "reasoning": a 2-3 sentence explanation of visual signals that led to this conclusion (e.g. lighting, textures, artifacts, uncanny details)`;

      const res = await invokeLLM({
        prompt,
        ...(mode === "image" && imageFile?.url ? { file_urls: [imageFile.url] } : {}),
        responseJsonSchema: {
          type: "object",
          properties: {
            verdict: { type: "string" },
            confidence: { type: "number" },
            reasoning: { type: "string" }
          },
          required: ["verdict", "confidence", "reasoning"]
        }
      });
      
      setResult(res);
    } catch (err) {
      console.error("Detection error:", err);
      setError("Failed to analyze content. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const clearAll = () => {
    setInput("");
    setImageFile(null);
    setResult(null);
    setError("");
  };

  const isAI = result?.verdict === "AI-Generated" || result?.verdict === "AI-Generated";
  const confidence = result?.confidence ?? 0;
  const canDetect = mode === "text" ? input.trim() : imageFile;

  return (
    <div className="flex flex-col h-full bg-[#111111] text-white p-4 gap-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <ScanSearch className="w-5 h-5 text-orange-400" />
          <h2 className="text-lg font-bold">AI Content Detector</h2>
        </div>
        {(input || imageFile || result) && (
          <button
            onClick={clearAll}
            className="text-white/40 hover:text-white/70 text-xs transition-colors"
          >
            Clear all
          </button>
        )}
      </div>

      {/* Mode toggle */}
      <div className="flex gap-2">
        <button
          onClick={() => { setMode("text"); setResult(null); setError(""); }}
          className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium transition-colors ${mode === "text" ? "bg-orange-500/20 text-orange-400 border border-orange-500/40" : "bg-white/5 text-white/50 hover:bg-white/10"}`}
        >
          <FileText className="w-4 h-4" /> Text
        </button>
        <button
          onClick={() => { setMode("image"); setResult(null); setError(""); }}
          className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium transition-colors ${mode === "image" ? "bg-orange-500/20 text-orange-400 border border-orange-500/40" : "bg-white/5 text-white/50 hover:bg-white/10"}`}
        >
          <ImageIcon className="w-4 h-4" /> Image
        </button>
      </div>

      {/* Input area */}
      {mode === "text" ? (
        <Textarea
          value={input}
          onChange={e => setInput(e.target.value)}
          placeholder="Paste text here to check if it was written by AI or a human..."
          className="flex-1 bg-[#1a1a1a] border-white/10 text-white resize-none min-h-[150px] focus-visible:border-orange-400/50"
        />
      ) : (
        <div
          onClick={() => fileInputRef.current?.click()}
          className="flex-1 min-h-[150px] bg-[#1a1a1a] border border-dashed border-white/20 rounded-xl flex flex-col items-center justify-center gap-3 cursor-pointer hover:border-orange-400/50 transition-colors relative overflow-hidden"
        >
          {imageFile ? (
            <>
              <img src={imageFile.preview} alt="preview" className="w-full h-full object-cover absolute inset-0 opacity-60 rounded-xl" />
              <div className="relative z-10 flex flex-col items-center gap-1 bg-black/50 p-2 rounded-lg">
                <span className="text-white/80 text-xs">{imageFile.name}</span>
                <button
                  onClick={e => { e.stopPropagation(); setImageFile(null); setResult(null); setError(""); }}
                  className="text-white/50 hover:text-red-400 transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </>
          ) : (
            <>
              <ImageIcon className="w-8 h-8 text-white/20" />
              <span className="text-white/40 text-sm">{uploading ? "Uploading..." : "Click to upload an image"}</span>
              <span className="text-white/20 text-xs">Max 10MB</span>
            </>
          )}
          <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handleImageChange} />
        </div>
      )}

      {/* Error message */}
      {error && (
        <div className="flex items-center gap-2 p-3 rounded-lg bg-red-400/10 border border-red-400/20">
          <AlertCircle className="w-4 h-4 text-red-400" />
          <p className="text-red-400 text-sm">{error}</p>
        </div>
      )}

      <Button
        onClick={detect}
        disabled={loading || uploading || !canDetect}
        className="bg-gradient-to-r from-orange-500 to-yellow-400 text-black font-semibold hover:opacity-90 transition-opacity"
      >
        {loading ? "Analyzing..." : "Detect"}
      </Button>

      {result && (
        <div className="bg-[#1a1a1a] border border-white/10 rounded-xl p-4 space-y-3 animate-in fade-in duration-300">
          <div className="flex items-center justify-between">
            <span className={`text-lg font-bold ${isAI ? "text-red-400" : "text-green-400"}`}>
              {result.verdict}
            </span>
            <span className="text-sm text-white/50">{confidence}% confident</span>
          </div>
          <div className="w-full h-2 rounded-full bg-white/10 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${isAI ? "bg-red-400" : "bg-green-400"}`}
              style={{ width: `${confidence}%` }}
            />
          </div>
          <p className="text-white/60 text-sm leading-relaxed">{result.reasoning}</p>
        </div>
      )}
    </div>
  );
}